# Generated by Django 3.2.5 on 2021-07-18 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Last_period_date', models.DateField()),
                ('Cycle_average', models.PositiveIntegerField()),
                ('Period_average', models.PositiveIntegerField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('cycle_event_date', models.DateField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
